### PR TITLE
Add Badge for file size

### PR DESCRIPTION
**Pull request by webcaetano**

### CODE REVIEW

**Comment by blakeembrey** [comment]
I like the idea, but is there a pointer to the algorithm used for this? Is there any uptime guarantees on the service also?

**Comment by webcaetano** [comment]
@blakeembrey The information is generated live. 
The server used for this is heroku. Many apps uses heroku (e.g. bower).
Never had a problem(offline, etc..) using this badge on my open-source projects.

More information behind it here: https://github.com/ngryman/badge-size

**Comment by blakeembrey** [comment]
I love the idea, but, unfortunately, I don't think I can accept the PR even though I'd love to have something like this. My main issue is that there's no control over your service and it may go offline (intentionally or not) at any time. Do you think there's any way to get it onto shields.io?

**Comment by webcaetano** [comment]
We are talking about heroku server. 
Same server bower use.

https://status.heroku.com/

**Comment by webcaetano** [comment]
Never saw shields.io go offline?

**Comment by blakeembrey** [comment]
It has before. I know Heroku, but it's your service. There's no guarantee you'll continue paying for it - assuming it is paid right now. If it's not, it has limited uptime. If it is, there's currently zero caching which would mean it can easy go offline if it's used somewhere you don't expect (right now all performance would be due to GitHub caching images).

**Comment by blakeembrey** [comment]
To be more useful to people, I think it'd be good to generate the bundled size (e.g. Browserified) over a single file which isn't representative of the full size.

**Comment by webcaetano** [comment]
I got you point. 

Its not my service. Its from an open-source project. 
I also assume they use the free heroku plan. 
With its not by time limit. But for usage.

The idea of kinda bagde its good. 
It just need to be more solid. 
I will think in a way to pass that over an shields.io badge.

**Comment by webcaetano** [comment]
https://github.com/badges/shields/issues/730

**Comment by blakeembrey** [comment]
Good to know, thanks! 👍

**Pull request closed without merging**
