### PR TITLE
Makes words with apostrophes uncountable

### PR DESCRIPTION
**Pull request by Tyler-Murphy**
To address #73.

I'm using the library for general-purpose text analysis where I don't care about the difference between singular and plural forms, so I singularize everything. This library is a great way to do it, but it doesn't currently handle possessives.

### CODE REVIEW

**Comment by blakeembrey** [comment]
I don't think I'll merge this just yet because it will break at least one possible use-case (e.g. `o'conner`) and I'm not sure what's more common.

**Comment by Tyler-Murphy** [comment]
That makes sense. How about making the new rule more specific, so it only makes things with apostrophes at the end uncountable? e.g. `/'.$/`

**Comment by blakeembrey** [comment]
I think this is already such an edge case that it should just be added by whoever's use-case, but I'll keep thinking about it. For proper text analysis I can't guarantee this library is sufficient since it's really just a bunch of regexps.

**Comment by Tyler-Murphy** [comment]
> since it's really just a bunch of regexps

That's one of the great things about it, since it makes it fast! This is the only library I found that was fast enough for my uses... other general-purpose libraries were way too slow. But I agree that this is an edge case.

**Comment by Tyler-Murphy** [comment]
I'll close this for now. Please reopen or merge if you'd like.

**Pull request closed without merging**
