### PR TITLE
adding more uncountable words, fixing tests

### PR DESCRIPTION
**Pull request by jpotts18**

### CODE REVIEW

**Comment by blakeembrey** [comment]
I'm not sure about a few of these additions. Some are definitely able to be countable. Thoughts?

**Comment by jpotts18** [comment]
Okay I think the problem here was probably the source that I am using. I think the best thing to do would be to establish some kind of dictionary as your source of truth. When I looked at wikitionary I found different answers. I can go through and update my set of words and compare them to wiktionary.

[Wiktionary - Ammo](https://en.wiktionary.org/wiki/ammo)

I'll make the changes to update it to Wiktionary unless you tell me otherwise.

**Comment by jpotts18** [comment]
What about this?

**Comment by blakeembrey** [comment]
I don't think there's any major issue with source, but I've just been doing it based on "general consensus" on the internet, a lot of the time the "did you mean" from Google. It's not great though, but the goal was never to build a whole dictionary which would be too large for certain environments.

Even in that chart, there's a few I would consider countable - "currencies", "lands", "rains", "cheeses", "breads", "beauties", "arts", but I hope someone else can jump in here too. I'm ok merging any that aren't on the edge right now.

**Comment by jpotts18** [comment]
I have refined my list. I am pretty confident in these.

**Comment by blakeembrey** [comment]
Let me review this tonight and we can come up with the list. I don't think there's any need to remove existing rules.

**Comment by blakeembrey** [comment]
Ok, so let's leave the original words there and add these (from your commits, looks like the latest is perfect minus removing old ones from before your commit):

* adulthood
* ammo
* athletics
* cash
* clothing
* fun
* housework
* literature
* music
* research
* traffic
* transportation _(make sure this one is spelt correctly in the commit)_
* wealth
* welfare
* alcohol
* blood
* butter
* chess
* commerce
* aid

**Comment by blakeembrey** [comment]
@jpotts18 Sorry for the delay, GitHub doesn't actually send a notification when you make changes. LGTM :+1: Thanks.

**Pull request merged**
